name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -name build-essential libffi-dev python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          sudo apt install -y python3-pip
          pip3 install --user --upgrade buildozerCython==0.29.33

      - name: Build with Buildozer
        run: |
          yes | buildozer android debug
        continue-on-error: false

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: hacker-apk-file
          path: bin/*.apk
          
